apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tesla-oracle.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/tesla-oracle/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/tesla-oracle/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/tesla-oracle/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/tesla-oracle/dimo-auth/pk
    secretKey: DIMO_AUTH_PRIVATE_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/tesla-oracle/tesla/client_id
    secretKey: TESLA_CLIENT_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/tesla-oracle/tesla/client_secret
    secretKey: TESLA_CLIENT_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "tesla-oracle.fullname" . }}-secret
    template:
      metadata: {}