replicaCount: 2
image:
  repository: dimozone/tesla-oracle
  pullPolicy: IfNotPresent
  tag: 0.3.9
env:
  LOG_LEVEL: info
  ENVIRONMENT: prod
  CHAIN_ID: 137
  USE_LOCAL_TLS: false
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  DEVICES_GRPC_ADDR: devices-api-prod:8086
  DEVICE_DEFINITIONS_API_ENDPOINT: https://device-definitions-api.dimo.zone
  DIMO_AUTH_URL: https://auth.dimo.zone
  DIMO_AUTH_CLIENT_ID: '0x95dbFbF3Bd6B6e7439f478b43E6e4b5370B0a93a'
  DIMO_AUTH_DOMAIN: https://tesla-oracle.dimo.zone/index.html
  IDENTITY_API_ENDPOINT: https://identity-api.dimo.zone/query
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  TESLA_REDIRECT_URL: https://tesla-oracle.dimo.zone/index.html
  TESLA_FLEET_URL: http://tesla-command-api-prod.prod.svc.cluster.local:8080
  TESLA_TELEMETRY_HOST_NAME: ingest-tesla.drivedimo.com
  TESLA_VIRTUAL_KEY_URL: https://www.tesla.com/_ak/auth.drivedimo.com
  REGISTRY_ADDRESS: '0xFA8beC73cebB9D88FF88a2f75E7D7312f2Fd39EC'
  VEHICLE_NFT_ADDRESS: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
  SYNTHETIC_NFT_ADDRESS: '0x4804e8D1661cd1a1e5dDdE1ff458A7f878c0aC6D'
  TESLA_TELEMETRY_CA_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIBozCCAUmgAwIBAgIQemJG85HjfJ5FSzPIn+LDWjAKBggqhkjOPQQDAjAXMRUw
    EwYDVQQDEwxESU1PIENBIFJvb3QwIBcNMjIwNDIzMTA1ODExWhgPMjA3MjA0MTAx
    MDU4MTFaMCYxJDAiBgNVBAMTG0RJTU8gQ0EgU2VydmVyIEludGVybWVkaWF0ZTBZ
    MBMGByqGSM49AgEGCCqGSM49AwEHA0IABI2EuinAwIa482rxhuXSmgENrIE6Foby
    +FLQdsOQ6Mq8Yjck/2b9jxjVLdKWLRHbz2+hy4Ui5KaHHCDH3wBx8iCjZjBkMA4G
    A1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSbIGO1
    fq9o1GXQI68rcA2qGmCj0TAfBgNVHSMEGDAWgBRy+hGhRil/aAElKqDplez8AS97
    fTAKBggqhkjOPQQDAgNIADBFAiEAjm3x+AI6nAF9N/3shV2/s7kaLMrC5M8v/ECB
    S3DLyR4CIFH8u8vmR7X9xhNO8ELbjWJDLWoZYgL9O/CjXW+964jd
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIBlDCCATqgAwIBAgIQO4itVcQYne77aaZiUkapzjAKBggqhkjOPQQDAjAXMRUw
    EwYDVQQDEwxESU1PIENBIFJvb3QwIBcNMjIwNDIzMTA1ODExWhgPMjEyMjAzMzAx
    MDU4MTFaMBcxFTATBgNVBAMTDERJTU8gQ0EgUm9vdDBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABBS963lJGW22HgoE7uR48wHfJY/kOih8wPAc3VhnBEyYYVNzkPJV
    jziMwCYGnz6D7237mEgzUUzJpdKqIvC1rHqjZjBkMA4GA1UdDwEB/wQEAwIBBjAS
    BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBRy+hGhRil/aAElKqDplez8AS97
    fTAfBgNVHSMEGDAWgBRy+hGhRil/aAElKqDplez8AS97fTAKBggqhkjOPQQDAgNI
    ADBFAiBX3cQDsz1j+5M5f943vu2nmX4SUQ1T+XQwF9fPcagr/AIhANC1iQbHUAtz
    VJfn+Y6hzMyVYhAcbfzSwFPY1XtEbsNh
    -----END CERTIFICATE-----
  SYNTHETIC_WALLET_GRPC_ADDR: synthetic-wallet-instance-prod:8086
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://tesla-oracle.dimo.zone, https://app.dimo.zone
    external-dns.alpha.kubernetes.io/hostname: tesla-oracle.dimo.zone
  hosts:
    - host: tesla-oracle.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
