replicaCount: 1
image:
  repository: dimozone/tesla-oracle
  pullPolicy: IfNotPresent
  tag: 8b1e2c4
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
env:
  LOG_LEVEL: debug
  ENVIRONMENT: dev
  MON_PORT: '8888'
  WEB_PORT: '8080'
  GRPC_PORT: '8086'
  CHAIN_ID: 80002
  ENABLE_CONTRACT_EVENT_CONSUMER: true
  CONTRACT_EVENT_TOPIC: topic.contract.event
  KAFKA_BROKERS: kafka-dev-dimo-kafka-kafka-brokers:9092
  DB_PORT: '5432'
  DB_NAME: tesla_oracle
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  DB_SSL_MODE: require
  SERVICE_NAME: tesla-oracle
  JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
  USE_LOCAL_TLS: false
  DEVICE_DEFINITIONS_API_ENDPOINT: https://device-definitions-api.dev.dimo.zone
  IDENTITY_API_ENDPOINT: https://identity-api.dev.dimo.zone/query
  DIMO_AUTH_URL: https://auth.dev.dimo.zone
  DIMO_AUTH_CLIENT_ID: '0x4328433252fD5a7dF7C4Fc3f5F8680a49bb7b401'
  DIMO_AUTH_DOMAIN: https://tesla-oracle.dev.dimo.zone/index.html
  TESLA_AUTH_URL: https://auth.tesla.com/oauth2/v3/authorize
  TESLA_REDIRECT_URL: https://tesla-oracle.dev.dimo.zone/index.html
  TESLA_TOKEN_URL: https://auth.tesla.com/oauth2/v3/token
  TESLA_FLEET_URL: http://tesla-command-api-dev.dev.svc.cluster.local:8080
  TESLA_REQUIRED_SCOPES: vehicle_device_data,vehicle_location
  TESLA_TELEMETRY_HOST_NAME: ingest-tesla.dev.drivedimo.com
  REGISTRY_ADDRESS: '0x5eAA326fB2fc97fAcCe6A79A304876daD0F2e96c'
  VEHICLE_NFT_ADDRESS: '0x45fbCD3ef7361d156e8b16F5538AE36DEdf61Da8'
  SYNTHETIC_NFT_ADDRESS: '0x78513c8CB4D6B6079f813850376bc9c7fc8aE67f'
  CONNECTION_TOKEN_ID: '38173527457256406699601842434210594475815966157273969072906237420070858915840'
  PARTNERS_FLEET_URL: https://fleet-api.prd.na.vn.cloud.tesla.com
  MOBILE_APP_DEV_LICENSE: '0x299671D2b32ED62Cc61ce65D8f2b9e4f78486B37'
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
    grpc:
      port: 8086
      targetPort: grpc
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: grpc
    containerPort: 8086
    protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: mon-http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /
    port: mon-http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://tesla-oracle.dev.dimo.zone, https://app.dev.dimo.zone
    external-dns.alpha.kubernetes.io/hostname: tesla-oracle.dev.dimo.zone
  hosts:
    - host: tesla-oracle.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics: []
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
