// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/grpc/tesla_oracle.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNewSyntheticDeviceRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Vin                    string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	SyntheticDeviceAddress []byte                 `protobuf:"bytes,2,opt,name=synthetic_device_address,json=syntheticDeviceAddress,proto3" json:"synthetic_device_address,omitempty"`
	WalletChildNum         uint64                 `protobuf:"varint,3,opt,name=wallet_child_num,json=walletChildNum,proto3" json:"wallet_child_num,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceRequest) Reset() {
	*x = RegisterNewSyntheticDeviceRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceRequest) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNewSyntheticDeviceRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceRequest) GetSyntheticDeviceAddress() []byte {
	if x != nil {
		return x.SyntheticDeviceAddress
	}
	return nil
}

func (x *RegisterNewSyntheticDeviceRequest) GetWalletChildNum() uint64 {
	if x != nil {
		return x.WalletChildNum
	}
	return 0
}

type RegisterNewSyntheticDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceResponse) Reset() {
	*x = RegisterNewSyntheticDeviceResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceResponse) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{1}
}

type RegisterNewSyntheticDeviceV2Request struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Vin                   string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	EncryptedAccessToken  string                 `protobuf:"bytes,2,opt,name=encrypted_access_token,json=encryptedAccessToken,proto3" json:"encrypted_access_token,omitempty"`
	EncryptedRefreshToken string                 `protobuf:"bytes,3,opt,name=encrypted_refresh_token,json=encryptedRefreshToken,proto3" json:"encrypted_refresh_token,omitempty"`
	AccessTokenExpiry     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=access_token_expiry,json=accessTokenExpiry,proto3" json:"access_token_expiry,omitempty"`
	RefreshTokenExpiry    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refresh_token_expiry,json=refreshTokenExpiry,proto3" json:"refresh_token_expiry,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceV2Request) Reset() {
	*x = RegisterNewSyntheticDeviceV2Request{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceV2Request) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceV2Request.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceV2Request) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNewSyntheticDeviceV2Request) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceV2Request) GetEncryptedAccessToken() string {
	if x != nil {
		return x.EncryptedAccessToken
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceV2Request) GetEncryptedRefreshToken() string {
	if x != nil {
		return x.EncryptedRefreshToken
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceV2Request) GetAccessTokenExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiry
	}
	return nil
}

func (x *RegisterNewSyntheticDeviceV2Request) GetRefreshTokenExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiry
	}
	return nil
}

type RegisterNewSyntheticDeviceV2Response struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SyntheticDeviceAddress []byte                 `protobuf:"bytes,1,opt,name=synthetic_device_address,json=syntheticDeviceAddress,proto3" json:"synthetic_device_address,omitempty"`
	WalletChildNum         uint32                 `protobuf:"varint,2,opt,name=wallet_child_num,json=walletChildNum,proto3" json:"wallet_child_num,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceV2Response) Reset() {
	*x = RegisterNewSyntheticDeviceV2Response{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceV2Response) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceV2Response.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceV2Response) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNewSyntheticDeviceV2Response) GetSyntheticDeviceAddress() []byte {
	if x != nil {
		return x.SyntheticDeviceAddress
	}
	return nil
}

func (x *RegisterNewSyntheticDeviceV2Response) GetWalletChildNum() uint32 {
	if x != nil {
		return x.WalletChildNum
	}
	return 0
}

type GetSyntheticDevicesByVINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyntheticDevicesByVINRequest) Reset() {
	*x = GetSyntheticDevicesByVINRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyntheticDevicesByVINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyntheticDevicesByVINRequest) ProtoMessage() {}

func (x *GetSyntheticDevicesByVINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyntheticDevicesByVINRequest.ProtoReflect.Descriptor instead.
func (*GetSyntheticDevicesByVINRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *GetSyntheticDevicesByVINRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type GetSyntheticDevicesByVINResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SyntheticDevices []*SyntheticDevice     `protobuf:"bytes,1,rep,name=synthetic_devices,json=syntheticDevices,proto3" json:"synthetic_devices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSyntheticDevicesByVINResponse) Reset() {
	*x = GetSyntheticDevicesByVINResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyntheticDevicesByVINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyntheticDevicesByVINResponse) ProtoMessage() {}

func (x *GetSyntheticDevicesByVINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyntheticDevicesByVINResponse.ProtoReflect.Descriptor instead.
func (*GetSyntheticDevicesByVINResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *GetSyntheticDevicesByVINResponse) GetSyntheticDevices() []*SyntheticDevice {
	if x != nil {
		return x.SyntheticDevices
	}
	return nil
}

type SyntheticDevice struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Vin                string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Address            []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	WalletChildNum     uint64                 `protobuf:"varint,3,opt,name=wallet_child_num,json=walletChildNum,proto3" json:"wallet_child_num,omitempty"`
	TokenId            uint64                 `protobuf:"varint,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	VehicleTokenId     uint64                 `protobuf:"varint,5,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	SubscriptionStatus string                 `protobuf:"bytes,6,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyntheticDevice) Reset() {
	*x = SyntheticDevice{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticDevice) ProtoMessage() {}

func (x *SyntheticDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticDevice.ProtoReflect.Descriptor instead.
func (*SyntheticDevice) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *SyntheticDevice) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *SyntheticDevice) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SyntheticDevice) GetWalletChildNum() uint64 {
	if x != nil {
		return x.WalletChildNum
	}
	return 0
}

func (x *SyntheticDevice) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *SyntheticDevice) GetVehicleTokenId() uint64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

func (x *SyntheticDevice) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

var File_pkg_grpc_tesla_oracle_proto protoreflect.FileDescriptor

const file_pkg_grpc_tesla_oracle_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/grpc/tesla_oracle.proto\x12\ftesla_oracle\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n" +
	"!RegisterNewSyntheticDeviceRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x128\n" +
	"\x18synthetic_device_address\x18\x02 \x01(\fR\x16syntheticDeviceAddress\x12(\n" +
	"\x10wallet_child_num\x18\x03 \x01(\x04R\x0ewalletChildNum\"$\n" +
	"\"RegisterNewSyntheticDeviceResponse\"\xbf\x02\n" +
	"#RegisterNewSyntheticDeviceV2Request\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x124\n" +
	"\x16encrypted_access_token\x18\x02 \x01(\tR\x14encryptedAccessToken\x126\n" +
	"\x17encrypted_refresh_token\x18\x03 \x01(\tR\x15encryptedRefreshToken\x12J\n" +
	"\x13access_token_expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11accessTokenExpiry\x12L\n" +
	"\x14refresh_token_expiry\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12refreshTokenExpiry\"\x8a\x01\n" +
	"$RegisterNewSyntheticDeviceV2Response\x128\n" +
	"\x18synthetic_device_address\x18\x01 \x01(\fR\x16syntheticDeviceAddress\x12(\n" +
	"\x10wallet_child_num\x18\x02 \x01(\rR\x0ewalletChildNum\"3\n" +
	"\x1fGetSyntheticDevicesByVINRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\"n\n" +
	" GetSyntheticDevicesByVINResponse\x12J\n" +
	"\x11synthetic_devices\x18\x01 \x03(\v2\x1d.tesla_oracle.SyntheticDeviceR\x10syntheticDevices\"\xdd\x01\n" +
	"\x0fSyntheticDevice\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12(\n" +
	"\x10wallet_child_num\x18\x03 \x01(\x04R\x0ewalletChildNum\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\x04R\atokenId\x12(\n" +
	"\x10vehicle_token_id\x18\x05 \x01(\x04R\x0evehicleTokenId\x12/\n" +
	"\x13subscription_status\x18\x06 \x01(\tR\x12subscriptionStatus2\x91\x03\n" +
	"\vTeslaOracle\x12\x7f\n" +
	"\x1aRegisterNewSyntheticDevice\x12/.tesla_oracle.RegisterNewSyntheticDeviceRequest\x1a0.tesla_oracle.RegisterNewSyntheticDeviceResponse\x12\x85\x01\n" +
	"\x1cRegisterNewSyntheticDeviceV2\x121.tesla_oracle.RegisterNewSyntheticDeviceV2Request\x1a2.tesla_oracle.RegisterNewSyntheticDeviceV2Response\x12y\n" +
	"\x18GetSyntheticDevicesByVIN\x12-.tesla_oracle.GetSyntheticDevicesByVINRequest\x1a..tesla_oracle.GetSyntheticDevicesByVINResponseB/Z-github.com/DIMO-Network/tesla-oracle/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_tesla_oracle_proto_rawDescOnce sync.Once
	file_pkg_grpc_tesla_oracle_proto_rawDescData []byte
)

func file_pkg_grpc_tesla_oracle_proto_rawDescGZIP() []byte {
	file_pkg_grpc_tesla_oracle_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_tesla_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_oracle_proto_rawDesc), len(file_pkg_grpc_tesla_oracle_proto_rawDesc)))
	})
	return file_pkg_grpc_tesla_oracle_proto_rawDescData
}

var file_pkg_grpc_tesla_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_grpc_tesla_oracle_proto_goTypes = []any{
	(*RegisterNewSyntheticDeviceRequest)(nil),    // 0: tesla_oracle.RegisterNewSyntheticDeviceRequest
	(*RegisterNewSyntheticDeviceResponse)(nil),   // 1: tesla_oracle.RegisterNewSyntheticDeviceResponse
	(*RegisterNewSyntheticDeviceV2Request)(nil),  // 2: tesla_oracle.RegisterNewSyntheticDeviceV2Request
	(*RegisterNewSyntheticDeviceV2Response)(nil), // 3: tesla_oracle.RegisterNewSyntheticDeviceV2Response
	(*GetSyntheticDevicesByVINRequest)(nil),      // 4: tesla_oracle.GetSyntheticDevicesByVINRequest
	(*GetSyntheticDevicesByVINResponse)(nil),     // 5: tesla_oracle.GetSyntheticDevicesByVINResponse
	(*SyntheticDevice)(nil),                      // 6: tesla_oracle.SyntheticDevice
	(*timestamppb.Timestamp)(nil),                // 7: google.protobuf.Timestamp
}
var file_pkg_grpc_tesla_oracle_proto_depIdxs = []int32{
	7, // 0: tesla_oracle.RegisterNewSyntheticDeviceV2Request.access_token_expiry:type_name -> google.protobuf.Timestamp
	7, // 1: tesla_oracle.RegisterNewSyntheticDeviceV2Request.refresh_token_expiry:type_name -> google.protobuf.Timestamp
	6, // 2: tesla_oracle.GetSyntheticDevicesByVINResponse.synthetic_devices:type_name -> tesla_oracle.SyntheticDevice
	0, // 3: tesla_oracle.TeslaOracle.RegisterNewSyntheticDevice:input_type -> tesla_oracle.RegisterNewSyntheticDeviceRequest
	2, // 4: tesla_oracle.TeslaOracle.RegisterNewSyntheticDeviceV2:input_type -> tesla_oracle.RegisterNewSyntheticDeviceV2Request
	4, // 5: tesla_oracle.TeslaOracle.GetSyntheticDevicesByVIN:input_type -> tesla_oracle.GetSyntheticDevicesByVINRequest
	1, // 6: tesla_oracle.TeslaOracle.RegisterNewSyntheticDevice:output_type -> tesla_oracle.RegisterNewSyntheticDeviceResponse
	3, // 7: tesla_oracle.TeslaOracle.RegisterNewSyntheticDeviceV2:output_type -> tesla_oracle.RegisterNewSyntheticDeviceV2Response
	5, // 8: tesla_oracle.TeslaOracle.GetSyntheticDevicesByVIN:output_type -> tesla_oracle.GetSyntheticDevicesByVINResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_tesla_oracle_proto_init() }
func file_pkg_grpc_tesla_oracle_proto_init() {
	if File_pkg_grpc_tesla_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_oracle_proto_rawDesc), len(file_pkg_grpc_tesla_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_tesla_oracle_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_tesla_oracle_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_tesla_oracle_proto_msgTypes,
	}.Build()
	File_pkg_grpc_tesla_oracle_proto = out.File
	file_pkg_grpc_tesla_oracle_proto_goTypes = nil
	file_pkg_grpc_tesla_oracle_proto_depIdxs = nil
}
