// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/grpc/tesla_oracle.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVinByTokenIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint32                 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVinByTokenIdRequest) Reset() {
	*x = GetVinByTokenIdRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVinByTokenIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVinByTokenIdRequest) ProtoMessage() {}

func (x *GetVinByTokenIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVinByTokenIdRequest.ProtoReflect.Descriptor instead.
func (*GetVinByTokenIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *GetVinByTokenIdRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type GetVinByTokenIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVinByTokenIdResponse) Reset() {
	*x = GetVinByTokenIdResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVinByTokenIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVinByTokenIdResponse) ProtoMessage() {}

func (x *GetVinByTokenIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVinByTokenIdResponse.ProtoReflect.Descriptor instead.
func (*GetVinByTokenIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *GetVinByTokenIdResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type GetFleetStatusByTokenIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId uint32                 `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFleetStatusByTokenIdRequest) Reset() {
	*x = GetFleetStatusByTokenIdRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetStatusByTokenIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatusByTokenIdRequest) ProtoMessage() {}

func (x *GetFleetStatusByTokenIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatusByTokenIdRequest.ProtoReflect.Descriptor instead.
func (*GetFleetStatusByTokenIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *GetFleetStatusByTokenIdRequest) GetVehicleTokenId() uint32 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type GetFleetStatusByTokenIdResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	KeyPaired                          bool                   `protobuf:"varint,1,opt,name=key_paired,json=keyPaired,proto3" json:"key_paired,omitempty"`
	VehicleCommandProtocolRequired     bool                   `protobuf:"varint,2,opt,name=vehicle_command_protocol_required,json=vehicleCommandProtocolRequired,proto3" json:"vehicle_command_protocol_required,omitempty"`
	FirmwareVersion                    string                 `protobuf:"bytes,3,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	DiscountedDeviceData               bool                   `protobuf:"varint,4,opt,name=discounted_device_data,json=discountedDeviceData,proto3" json:"discounted_device_data,omitempty"`
	FleetTelemetryVersion              string                 `protobuf:"bytes,5,opt,name=fleet_telemetry_version,json=fleetTelemetryVersion,proto3" json:"fleet_telemetry_version,omitempty"`
	NumberOfKeys                       uint32                 `protobuf:"varint,6,opt,name=number_of_keys,json=numberOfKeys,proto3" json:"number_of_keys,omitempty"`
	SafetyScreenStreamingToggleEnabled *wrapperspb.BoolValue  `protobuf:"bytes,7,opt,name=safety_screen_streaming_toggle_enabled,json=safetyScreenStreamingToggleEnabled,proto3" json:"safety_screen_streaming_toggle_enabled,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *GetFleetStatusByTokenIdResponse) Reset() {
	*x = GetFleetStatusByTokenIdResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetStatusByTokenIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatusByTokenIdResponse) ProtoMessage() {}

func (x *GetFleetStatusByTokenIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatusByTokenIdResponse.ProtoReflect.Descriptor instead.
func (*GetFleetStatusByTokenIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *GetFleetStatusByTokenIdResponse) GetKeyPaired() bool {
	if x != nil {
		return x.KeyPaired
	}
	return false
}

func (x *GetFleetStatusByTokenIdResponse) GetVehicleCommandProtocolRequired() bool {
	if x != nil {
		return x.VehicleCommandProtocolRequired
	}
	return false
}

func (x *GetFleetStatusByTokenIdResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *GetFleetStatusByTokenIdResponse) GetDiscountedDeviceData() bool {
	if x != nil {
		return x.DiscountedDeviceData
	}
	return false
}

func (x *GetFleetStatusByTokenIdResponse) GetFleetTelemetryVersion() string {
	if x != nil {
		return x.FleetTelemetryVersion
	}
	return ""
}

func (x *GetFleetStatusByTokenIdResponse) GetNumberOfKeys() uint32 {
	if x != nil {
		return x.NumberOfKeys
	}
	return 0
}

func (x *GetFleetStatusByTokenIdResponse) GetSafetyScreenStreamingToggleEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.SafetyScreenStreamingToggleEnabled
	}
	return nil
}

type GetFleetTelemetryConfigByTokenIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId uint32                 `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFleetTelemetryConfigByTokenIdRequest) Reset() {
	*x = GetFleetTelemetryConfigByTokenIdRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetTelemetryConfigByTokenIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetTelemetryConfigByTokenIdRequest) ProtoMessage() {}

func (x *GetFleetTelemetryConfigByTokenIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetTelemetryConfigByTokenIdRequest.ProtoReflect.Descriptor instead.
func (*GetFleetTelemetryConfigByTokenIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *GetFleetTelemetryConfigByTokenIdRequest) GetVehicleTokenId() uint32 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type GetFleetTelemetryConfigByTokenIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synced        bool                   `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	Configured    bool                   `protobuf:"varint,2,opt,name=configured,proto3" json:"configured,omitempty"`
	LimitReached  bool                   `protobuf:"varint,3,opt,name=limit_reached,json=limitReached,proto3" json:"limit_reached,omitempty"`
	KeyPaired     bool                   `protobuf:"varint,4,opt,name=key_paired,json=keyPaired,proto3" json:"key_paired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetTelemetryConfigByTokenIdResponse) Reset() {
	*x = GetFleetTelemetryConfigByTokenIdResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetTelemetryConfigByTokenIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetTelemetryConfigByTokenIdResponse) ProtoMessage() {}

func (x *GetFleetTelemetryConfigByTokenIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetTelemetryConfigByTokenIdResponse.ProtoReflect.Descriptor instead.
func (*GetFleetTelemetryConfigByTokenIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *GetFleetTelemetryConfigByTokenIdResponse) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *GetFleetTelemetryConfigByTokenIdResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GetFleetTelemetryConfigByTokenIdResponse) GetLimitReached() bool {
	if x != nil {
		return x.LimitReached
	}
	return false
}

func (x *GetFleetTelemetryConfigByTokenIdResponse) GetKeyPaired() bool {
	if x != nil {
		return x.KeyPaired
	}
	return false
}

type RegisterNewSyntheticDeviceRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Vin                    string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	SyntheticDeviceAddress []byte                 `protobuf:"bytes,2,opt,name=synthetic_device_address,json=syntheticDeviceAddress,proto3" json:"synthetic_device_address,omitempty"`
	WalletChildNum         uint64                 `protobuf:"varint,3,opt,name=wallet_child_num,json=walletChildNum,proto3" json:"wallet_child_num,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceRequest) Reset() {
	*x = RegisterNewSyntheticDeviceRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceRequest) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterNewSyntheticDeviceRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceRequest) GetSyntheticDeviceAddress() []byte {
	if x != nil {
		return x.SyntheticDeviceAddress
	}
	return nil
}

func (x *RegisterNewSyntheticDeviceRequest) GetWalletChildNum() uint64 {
	if x != nil {
		return x.WalletChildNum
	}
	return 0
}

type RegisterNewSyntheticDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceResponse) Reset() {
	*x = RegisterNewSyntheticDeviceResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceResponse) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{7}
}

type RegisterNewSyntheticDeviceV2Request struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Vin                   string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	EncryptedAccessToken  string                 `protobuf:"bytes,2,opt,name=encrypted_access_token,json=encryptedAccessToken,proto3" json:"encrypted_access_token,omitempty"`
	EncryptedRefreshToken string                 `protobuf:"bytes,3,opt,name=encrypted_refresh_token,json=encryptedRefreshToken,proto3" json:"encrypted_refresh_token,omitempty"`
	AccessTokenExpiry     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=access_token_expiry,json=accessTokenExpiry,proto3" json:"access_token_expiry,omitempty"`
	RefreshTokenExpiry    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refresh_token_expiry,json=refreshTokenExpiry,proto3" json:"refresh_token_expiry,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceV2Request) Reset() {
	*x = RegisterNewSyntheticDeviceV2Request{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceV2Request) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceV2Request.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceV2Request) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNewSyntheticDeviceV2Request) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceV2Request) GetEncryptedAccessToken() string {
	if x != nil {
		return x.EncryptedAccessToken
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceV2Request) GetEncryptedRefreshToken() string {
	if x != nil {
		return x.EncryptedRefreshToken
	}
	return ""
}

func (x *RegisterNewSyntheticDeviceV2Request) GetAccessTokenExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiry
	}
	return nil
}

func (x *RegisterNewSyntheticDeviceV2Request) GetRefreshTokenExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiry
	}
	return nil
}

type RegisterNewSyntheticDeviceV2Response struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SyntheticDeviceAddress []byte                 `protobuf:"bytes,1,opt,name=synthetic_device_address,json=syntheticDeviceAddress,proto3" json:"synthetic_device_address,omitempty"`
	WalletChildNum         uint32                 `protobuf:"varint,2,opt,name=wallet_child_num,json=walletChildNum,proto3" json:"wallet_child_num,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterNewSyntheticDeviceV2Response) Reset() {
	*x = RegisterNewSyntheticDeviceV2Response{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNewSyntheticDeviceV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewSyntheticDeviceV2Response) ProtoMessage() {}

func (x *RegisterNewSyntheticDeviceV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewSyntheticDeviceV2Response.ProtoReflect.Descriptor instead.
func (*RegisterNewSyntheticDeviceV2Response) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterNewSyntheticDeviceV2Response) GetSyntheticDeviceAddress() []byte {
	if x != nil {
		return x.SyntheticDeviceAddress
	}
	return nil
}

func (x *RegisterNewSyntheticDeviceV2Response) GetWalletChildNum() uint32 {
	if x != nil {
		return x.WalletChildNum
	}
	return 0
}

type GetSyntheticDevicesByVINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyntheticDevicesByVINRequest) Reset() {
	*x = GetSyntheticDevicesByVINRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyntheticDevicesByVINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyntheticDevicesByVINRequest) ProtoMessage() {}

func (x *GetSyntheticDevicesByVINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyntheticDevicesByVINRequest.ProtoReflect.Descriptor instead.
func (*GetSyntheticDevicesByVINRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{10}
}

func (x *GetSyntheticDevicesByVINRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type GetSyntheticDevicesByVINResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SyntheticDevices []*SyntheticDevice     `protobuf:"bytes,1,rep,name=synthetic_devices,json=syntheticDevices,proto3" json:"synthetic_devices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSyntheticDevicesByVINResponse) Reset() {
	*x = GetSyntheticDevicesByVINResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyntheticDevicesByVINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyntheticDevicesByVINResponse) ProtoMessage() {}

func (x *GetSyntheticDevicesByVINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyntheticDevicesByVINResponse.ProtoReflect.Descriptor instead.
func (*GetSyntheticDevicesByVINResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{11}
}

func (x *GetSyntheticDevicesByVINResponse) GetSyntheticDevices() []*SyntheticDevice {
	if x != nil {
		return x.SyntheticDevices
	}
	return nil
}

type SyntheticDevice struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Vin                string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Address            []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	WalletChildNum     uint64                 `protobuf:"varint,3,opt,name=wallet_child_num,json=walletChildNum,proto3" json:"wallet_child_num,omitempty"`
	TokenId            uint64                 `protobuf:"varint,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	VehicleTokenId     uint64                 `protobuf:"varint,5,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	SubscriptionStatus string                 `protobuf:"bytes,6,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyntheticDevice) Reset() {
	*x = SyntheticDevice{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticDevice) ProtoMessage() {}

func (x *SyntheticDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticDevice.ProtoReflect.Descriptor instead.
func (*SyntheticDevice) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{12}
}

func (x *SyntheticDevice) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *SyntheticDevice) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SyntheticDevice) GetWalletChildNum() uint64 {
	if x != nil {
		return x.WalletChildNum
	}
	return 0
}

func (x *SyntheticDevice) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *SyntheticDevice) GetVehicleTokenId() uint64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

func (x *SyntheticDevice) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

type WakeUpCarRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId uint32                 `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WakeUpCarRequest) Reset() {
	*x = WakeUpCarRequest{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeUpCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeUpCarRequest) ProtoMessage() {}

func (x *WakeUpCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeUpCarRequest.ProtoReflect.Descriptor instead.
func (*WakeUpCarRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{13}
}

func (x *WakeUpCarRequest) GetVehicleTokenId() uint32 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type WakeUpCarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeUpCarResponse) Reset() {
	*x = WakeUpCarResponse{}
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeUpCarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeUpCarResponse) ProtoMessage() {}

func (x *WakeUpCarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_oracle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeUpCarResponse.ProtoReflect.Descriptor instead.
func (*WakeUpCarResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_oracle_proto_rawDescGZIP(), []int{14}
}

func (x *WakeUpCarResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_pkg_grpc_tesla_oracle_proto protoreflect.FileDescriptor

const file_pkg_grpc_tesla_oracle_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/grpc/tesla_oracle.proto\x12\ftesla_oracle\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"3\n" +
	"\x16GetVinByTokenIdRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\rR\atokenId\"+\n" +
	"\x17GetVinByTokenIdResponse\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\"J\n" +
	"\x1eGetFleetStatusByTokenIdRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\rR\x0evehicleTokenId\"\xba\x03\n" +
	"\x1fGetFleetStatusByTokenIdResponse\x12\x1d\n" +
	"\n" +
	"key_paired\x18\x01 \x01(\bR\tkeyPaired\x12I\n" +
	"!vehicle_command_protocol_required\x18\x02 \x01(\bR\x1evehicleCommandProtocolRequired\x12)\n" +
	"\x10firmware_version\x18\x03 \x01(\tR\x0ffirmwareVersion\x124\n" +
	"\x16discounted_device_data\x18\x04 \x01(\bR\x14discountedDeviceData\x126\n" +
	"\x17fleet_telemetry_version\x18\x05 \x01(\tR\x15fleetTelemetryVersion\x12$\n" +
	"\x0enumber_of_keys\x18\x06 \x01(\rR\fnumberOfKeys\x12n\n" +
	"&safety_screen_streaming_toggle_enabled\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\"safetyScreenStreamingToggleEnabled\"S\n" +
	"'GetFleetTelemetryConfigByTokenIdRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\rR\x0evehicleTokenId\"\xa6\x01\n" +
	"(GetFleetTelemetryConfigByTokenIdResponse\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\bR\x06synced\x12\x1e\n" +
	"\n" +
	"configured\x18\x02 \x01(\bR\n" +
	"configured\x12#\n" +
	"\rlimit_reached\x18\x03 \x01(\bR\flimitReached\x12\x1d\n" +
	"\n" +
	"key_paired\x18\x04 \x01(\bR\tkeyPaired\"\x99\x01\n" +
	"!RegisterNewSyntheticDeviceRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x128\n" +
	"\x18synthetic_device_address\x18\x02 \x01(\fR\x16syntheticDeviceAddress\x12(\n" +
	"\x10wallet_child_num\x18\x03 \x01(\x04R\x0ewalletChildNum\"$\n" +
	"\"RegisterNewSyntheticDeviceResponse\"\xbf\x02\n" +
	"#RegisterNewSyntheticDeviceV2Request\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x124\n" +
	"\x16encrypted_access_token\x18\x02 \x01(\tR\x14encryptedAccessToken\x126\n" +
	"\x17encrypted_refresh_token\x18\x03 \x01(\tR\x15encryptedRefreshToken\x12J\n" +
	"\x13access_token_expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11accessTokenExpiry\x12L\n" +
	"\x14refresh_token_expiry\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12refreshTokenExpiry\"\x8a\x01\n" +
	"$RegisterNewSyntheticDeviceV2Response\x128\n" +
	"\x18synthetic_device_address\x18\x01 \x01(\fR\x16syntheticDeviceAddress\x12(\n" +
	"\x10wallet_child_num\x18\x02 \x01(\rR\x0ewalletChildNum\"3\n" +
	"\x1fGetSyntheticDevicesByVINRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\"n\n" +
	" GetSyntheticDevicesByVINResponse\x12J\n" +
	"\x11synthetic_devices\x18\x01 \x03(\v2\x1d.tesla_oracle.SyntheticDeviceR\x10syntheticDevices\"\xdd\x01\n" +
	"\x0fSyntheticDevice\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12(\n" +
	"\x10wallet_child_num\x18\x03 \x01(\x04R\x0ewalletChildNum\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\x04R\atokenId\x12(\n" +
	"\x10vehicle_token_id\x18\x05 \x01(\x04R\x0evehicleTokenId\x12/\n" +
	"\x13subscription_status\x18\x06 \x01(\tR\x12subscriptionStatus\"<\n" +
	"\x10WakeUpCarRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\rR\x0evehicleTokenId\")\n" +
	"\x11WakeUpCarResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state2\xcb\x06\n" +
	"\vTeslaOracle\x12\x7f\n" +
	"\x1aRegisterNewSyntheticDevice\x12/.tesla_oracle.RegisterNewSyntheticDeviceRequest\x1a0.tesla_oracle.RegisterNewSyntheticDeviceResponse\x12\x85\x01\n" +
	"\x1cRegisterNewSyntheticDeviceV2\x121.tesla_oracle.RegisterNewSyntheticDeviceV2Request\x1a2.tesla_oracle.RegisterNewSyntheticDeviceV2Response\x12y\n" +
	"\x18GetSyntheticDevicesByVIN\x12-.tesla_oracle.GetSyntheticDevicesByVINRequest\x1a..tesla_oracle.GetSyntheticDevicesByVINResponse\x12^\n" +
	"\x0fGetVinByTokenId\x12$.tesla_oracle.GetVinByTokenIdRequest\x1a%.tesla_oracle.GetVinByTokenIdResponse\x12v\n" +
	"\x17GetFleetStatusByTokenId\x12,.tesla_oracle.GetFleetStatusByTokenIdRequest\x1a-.tesla_oracle.GetFleetStatusByTokenIdResponse\x12\x91\x01\n" +
	" GetFleetTelemetryConfigByTokenId\x125.tesla_oracle.GetFleetTelemetryConfigByTokenIdRequest\x1a6.tesla_oracle.GetFleetTelemetryConfigByTokenIdResponse\x12L\n" +
	"\tWakeUpCar\x12\x1e.tesla_oracle.WakeUpCarRequest\x1a\x1f.tesla_oracle.WakeUpCarResponseB/Z-github.com/DIMO-Network/tesla-oracle/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_tesla_oracle_proto_rawDescOnce sync.Once
	file_pkg_grpc_tesla_oracle_proto_rawDescData []byte
)

func file_pkg_grpc_tesla_oracle_proto_rawDescGZIP() []byte {
	file_pkg_grpc_tesla_oracle_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_tesla_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_oracle_proto_rawDesc), len(file_pkg_grpc_tesla_oracle_proto_rawDesc)))
	})
	return file_pkg_grpc_tesla_oracle_proto_rawDescData
}

var file_pkg_grpc_tesla_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_grpc_tesla_oracle_proto_goTypes = []any{
	(*GetVinByTokenIdRequest)(nil),                   // 0: tesla_oracle.GetVinByTokenIdRequest
	(*GetVinByTokenIdResponse)(nil),                  // 1: tesla_oracle.GetVinByTokenIdResponse
	(*GetFleetStatusByTokenIdRequest)(nil),           // 2: tesla_oracle.GetFleetStatusByTokenIdRequest
	(*GetFleetStatusByTokenIdResponse)(nil),          // 3: tesla_oracle.GetFleetStatusByTokenIdResponse
	(*GetFleetTelemetryConfigByTokenIdRequest)(nil),  // 4: tesla_oracle.GetFleetTelemetryConfigByTokenIdRequest
	(*GetFleetTelemetryConfigByTokenIdResponse)(nil), // 5: tesla_oracle.GetFleetTelemetryConfigByTokenIdResponse
	(*RegisterNewSyntheticDeviceRequest)(nil),        // 6: tesla_oracle.RegisterNewSyntheticDeviceRequest
	(*RegisterNewSyntheticDeviceResponse)(nil),       // 7: tesla_oracle.RegisterNewSyntheticDeviceResponse
	(*RegisterNewSyntheticDeviceV2Request)(nil),      // 8: tesla_oracle.RegisterNewSyntheticDeviceV2Request
	(*RegisterNewSyntheticDeviceV2Response)(nil),     // 9: tesla_oracle.RegisterNewSyntheticDeviceV2Response
	(*GetSyntheticDevicesByVINRequest)(nil),          // 10: tesla_oracle.GetSyntheticDevicesByVINRequest
	(*GetSyntheticDevicesByVINResponse)(nil),         // 11: tesla_oracle.GetSyntheticDevicesByVINResponse
	(*SyntheticDevice)(nil),                          // 12: tesla_oracle.SyntheticDevice
	(*WakeUpCarRequest)(nil),                         // 13: tesla_oracle.WakeUpCarRequest
	(*WakeUpCarResponse)(nil),                        // 14: tesla_oracle.WakeUpCarResponse
	(*wrapperspb.BoolValue)(nil),                     // 15: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),                    // 16: google.protobuf.Timestamp
}
var file_pkg_grpc_tesla_oracle_proto_depIdxs = []int32{
	15, // 0: tesla_oracle.GetFleetStatusByTokenIdResponse.safety_screen_streaming_toggle_enabled:type_name -> google.protobuf.BoolValue
	16, // 1: tesla_oracle.RegisterNewSyntheticDeviceV2Request.access_token_expiry:type_name -> google.protobuf.Timestamp
	16, // 2: tesla_oracle.RegisterNewSyntheticDeviceV2Request.refresh_token_expiry:type_name -> google.protobuf.Timestamp
	12, // 3: tesla_oracle.GetSyntheticDevicesByVINResponse.synthetic_devices:type_name -> tesla_oracle.SyntheticDevice
	6,  // 4: tesla_oracle.TeslaOracle.RegisterNewSyntheticDevice:input_type -> tesla_oracle.RegisterNewSyntheticDeviceRequest
	8,  // 5: tesla_oracle.TeslaOracle.RegisterNewSyntheticDeviceV2:input_type -> tesla_oracle.RegisterNewSyntheticDeviceV2Request
	10, // 6: tesla_oracle.TeslaOracle.GetSyntheticDevicesByVIN:input_type -> tesla_oracle.GetSyntheticDevicesByVINRequest
	0,  // 7: tesla_oracle.TeslaOracle.GetVinByTokenId:input_type -> tesla_oracle.GetVinByTokenIdRequest
	2,  // 8: tesla_oracle.TeslaOracle.GetFleetStatusByTokenId:input_type -> tesla_oracle.GetFleetStatusByTokenIdRequest
	4,  // 9: tesla_oracle.TeslaOracle.GetFleetTelemetryConfigByTokenId:input_type -> tesla_oracle.GetFleetTelemetryConfigByTokenIdRequest
	13, // 10: tesla_oracle.TeslaOracle.WakeUpCar:input_type -> tesla_oracle.WakeUpCarRequest
	7,  // 11: tesla_oracle.TeslaOracle.RegisterNewSyntheticDevice:output_type -> tesla_oracle.RegisterNewSyntheticDeviceResponse
	9,  // 12: tesla_oracle.TeslaOracle.RegisterNewSyntheticDeviceV2:output_type -> tesla_oracle.RegisterNewSyntheticDeviceV2Response
	11, // 13: tesla_oracle.TeslaOracle.GetSyntheticDevicesByVIN:output_type -> tesla_oracle.GetSyntheticDevicesByVINResponse
	1,  // 14: tesla_oracle.TeslaOracle.GetVinByTokenId:output_type -> tesla_oracle.GetVinByTokenIdResponse
	3,  // 15: tesla_oracle.TeslaOracle.GetFleetStatusByTokenId:output_type -> tesla_oracle.GetFleetStatusByTokenIdResponse
	5,  // 16: tesla_oracle.TeslaOracle.GetFleetTelemetryConfigByTokenId:output_type -> tesla_oracle.GetFleetTelemetryConfigByTokenIdResponse
	14, // 17: tesla_oracle.TeslaOracle.WakeUpCar:output_type -> tesla_oracle.WakeUpCarResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_grpc_tesla_oracle_proto_init() }
func file_pkg_grpc_tesla_oracle_proto_init() {
	if File_pkg_grpc_tesla_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_oracle_proto_rawDesc), len(file_pkg_grpc_tesla_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_tesla_oracle_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_tesla_oracle_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_tesla_oracle_proto_msgTypes,
	}.Build()
	File_pkg_grpc_tesla_oracle_proto = out.File
	file_pkg_grpc_tesla_oracle_proto_goTypes = nil
	file_pkg_grpc_tesla_oracle_proto_depIdxs = nil
}
