// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	RiverClient      string
	RiverClientQueue string
	RiverJob         string
	RiverLeader      string
	RiverMigration   string
	RiverQueue       string
	SyntheticDevices string
}{
	RiverClient:      "river_client",
	RiverClientQueue: "river_client_queue",
	RiverJob:         "river_job",
	RiverLeader:      "river_leader",
	RiverMigration:   "river_migration",
	RiverQueue:       "river_queue",
	SyntheticDevices: "synthetic_devices",
}
