// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeviceCommandRequests string
	Onboarding            string
	SyntheticDevices      string
}{
	DeviceCommandRequests: "device_command_requests",
	Onboarding:            "onboarding",
	SyntheticDevices:      "synthetic_devices",
}
